// Code generated by ent, DO NOT EDIT.

package fulltxt

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fulltxt type in the database.
	Label = "fulltxt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTxt holds the string denoting the txt field in the database.
	FieldTxt = "txt"
	// Table holds the table name of the fulltxt in the database.
	Table = "fulltxts"
)

// Columns holds all SQL columns for fulltxt fields.
var Columns = []string{
	FieldID,
	FieldTxt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Fulltxt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTxt orders the results by the txt field.
func ByTxt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxt, opts...).ToFunc()
}
