// Code generated by ent, DO NOT EDIT.

package entgeo

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the geo type in the database.
	Label = "geo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPoint holds the string denoting the point field in the database.
	FieldPoint = "point"
	// Table holds the table name of the geo in the database.
	Table = "geos"
)

// Columns holds all SQL columns for geo fields.
var Columns = []string{
	FieldID,
	FieldPoint,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Geo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPoint orders the results by the point field.
func ByPoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoint, opts...).ToFunc()
}
