// Code generated by ent, DO NOT EDIT.

package entgeo

import (
	"entgo.io/ent/dialect/sql"
	"github.com/tonimaru/try-ent/ent/predicate"
	"github.com/tonimaru/try-ent/pkg/geo"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Geo {
	return predicate.Geo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Geo {
	return predicate.Geo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Geo {
	return predicate.Geo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Geo {
	return predicate.Geo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Geo {
	return predicate.Geo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Geo {
	return predicate.Geo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Geo {
	return predicate.Geo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Geo {
	return predicate.Geo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Geo {
	return predicate.Geo(sql.FieldLTE(FieldID, id))
}

// Point applies equality check predicate on the "point" field. It's identical to PointEQ.
func Point(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldEQ(FieldPoint, v))
}

// PointEQ applies the EQ predicate on the "point" field.
func PointEQ(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldEQ(FieldPoint, v))
}

// PointNEQ applies the NEQ predicate on the "point" field.
func PointNEQ(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldNEQ(FieldPoint, v))
}

// PointIn applies the In predicate on the "point" field.
func PointIn(vs ...*geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldIn(FieldPoint, vs...))
}

// PointNotIn applies the NotIn predicate on the "point" field.
func PointNotIn(vs ...*geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldNotIn(FieldPoint, vs...))
}

// PointGT applies the GT predicate on the "point" field.
func PointGT(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldGT(FieldPoint, v))
}

// PointGTE applies the GTE predicate on the "point" field.
func PointGTE(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldGTE(FieldPoint, v))
}

// PointLT applies the LT predicate on the "point" field.
func PointLT(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldLT(FieldPoint, v))
}

// PointLTE applies the LTE predicate on the "point" field.
func PointLTE(v *geo.Point) predicate.Geo {
	return predicate.Geo(sql.FieldLTE(FieldPoint, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Geo) predicate.Geo {
	return predicate.Geo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Geo) predicate.Geo {
	return predicate.Geo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Geo) predicate.Geo {
	return predicate.Geo(func(s *sql.Selector) {
		p(s.Not())
	})
}
