// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FulltxtsColumns holds the columns for the "fulltxts" table.
	FulltxtsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "txt", Type: field.TypeString, Size: 2147483647},
	}
	// FulltxtsTable holds the schema information for the "fulltxts" table.
	FulltxtsTable = &schema.Table{
		Name:       "fulltxts",
		Columns:    FulltxtsColumns,
		PrimaryKey: []*schema.Column{FulltxtsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fulltxt_txt",
				Unique:  false,
				Columns: []*schema.Column{FulltxtsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Type: "FULLTEXT",
				},
			},
		},
	}
	// GeosColumns holds the columns for the "geos" table.
	GeosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "point", Type: field.TypeOther, SchemaType: map[string]string{"mysql": "POINT"}},
	}
	// GeosTable holds the schema information for the "geos" table.
	GeosTable = &schema.Table{
		Name:       "geos",
		Columns:    GeosColumns,
		PrimaryKey: []*schema.Column{GeosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FulltxtsTable,
		GeosTable,
	}
)

func init() {
}
