// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tonimaru/try-ent/ent/fulltxt"
)

// Fulltxt is the model entity for the Fulltxt schema.
type Fulltxt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Txt holds the value of the "txt" field.
	Txt          string `json:"txt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Fulltxt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fulltxt.FieldID:
			values[i] = new(sql.NullInt64)
		case fulltxt.FieldTxt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Fulltxt fields.
func (f *Fulltxt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fulltxt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = int(value.Int64)
		case fulltxt.FieldTxt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field txt", values[i])
			} else if value.Valid {
				f.Txt = value.String
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Fulltxt.
// This includes values selected through modifiers, order, etc.
func (f *Fulltxt) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// Update returns a builder for updating this Fulltxt.
// Note that you need to call Fulltxt.Unwrap() before calling this method if this Fulltxt
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Fulltxt) Update() *FulltxtUpdateOne {
	return NewFulltxtClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the Fulltxt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Fulltxt) Unwrap() *Fulltxt {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Fulltxt is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Fulltxt) String() string {
	var builder strings.Builder
	builder.WriteString("Fulltxt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	builder.WriteString("txt=")
	builder.WriteString(f.Txt)
	builder.WriteByte(')')
	return builder.String()
}

// Fulltxts is a parsable slice of Fulltxt.
type Fulltxts []*Fulltxt
