// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	entgeo "github.com/tonimaru/try-ent/ent/geo"
	"github.com/tonimaru/try-ent/ent/predicate"
	"github.com/tonimaru/try-ent/pkg/geo"
)

// GeoUpdate is the builder for updating Geo entities.
type GeoUpdate struct {
	config
	hooks     []Hook
	mutation  *GeoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GeoUpdate builder.
func (gu *GeoUpdate) Where(ps ...predicate.Geo) *GeoUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetPoint sets the "point" field.
func (gu *GeoUpdate) SetPoint(ge *geo.Point) *GeoUpdate {
	gu.mutation.SetPoint(ge)
	return gu
}

// Mutation returns the GeoMutation object of the builder.
func (gu *GeoUpdate) Mutation() *GeoMutation {
	return gu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GeoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GeoUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GeoUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GeoUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (gu *GeoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GeoUpdate {
	gu.modifiers = append(gu.modifiers, modifiers...)
	return gu
}

func (gu *GeoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entgeo.Table, entgeo.Columns, sqlgraph.NewFieldSpec(entgeo.FieldID, field.TypeInt))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Point(); ok {
		_spec.SetField(entgeo.FieldPoint, field.TypeOther, value)
	}
	_spec.AddModifiers(gu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entgeo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GeoUpdateOne is the builder for updating a single Geo entity.
type GeoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GeoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPoint sets the "point" field.
func (guo *GeoUpdateOne) SetPoint(ge *geo.Point) *GeoUpdateOne {
	guo.mutation.SetPoint(ge)
	return guo
}

// Mutation returns the GeoMutation object of the builder.
func (guo *GeoUpdateOne) Mutation() *GeoMutation {
	return guo.mutation
}

// Where appends a list predicates to the GeoUpdate builder.
func (guo *GeoUpdateOne) Where(ps ...predicate.Geo) *GeoUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GeoUpdateOne) Select(field string, fields ...string) *GeoUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Geo entity.
func (guo *GeoUpdateOne) Save(ctx context.Context) (*Geo, error) {
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GeoUpdateOne) SaveX(ctx context.Context) *Geo {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GeoUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GeoUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (guo *GeoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GeoUpdateOne {
	guo.modifiers = append(guo.modifiers, modifiers...)
	return guo
}

func (guo *GeoUpdateOne) sqlSave(ctx context.Context) (_node *Geo, err error) {
	_spec := sqlgraph.NewUpdateSpec(entgeo.Table, entgeo.Columns, sqlgraph.NewFieldSpec(entgeo.FieldID, field.TypeInt))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Geo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entgeo.FieldID)
		for _, f := range fields {
			if !entgeo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entgeo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Point(); ok {
		_spec.SetField(entgeo.FieldPoint, field.TypeOther, value)
	}
	_spec.AddModifiers(guo.modifiers...)
	_node = &Geo{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entgeo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
