// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	entgeo "github.com/tonimaru/try-ent/ent/geo"
	"github.com/tonimaru/try-ent/pkg/geo"
)

// GeoCreate is the builder for creating a Geo entity.
type GeoCreate struct {
	config
	mutation *GeoMutation
	hooks    []Hook
}

// SetPoint sets the "point" field.
func (gc *GeoCreate) SetPoint(ge *geo.Point) *GeoCreate {
	gc.mutation.SetPoint(ge)
	return gc
}

// Mutation returns the GeoMutation object of the builder.
func (gc *GeoCreate) Mutation() *GeoMutation {
	return gc.mutation
}

// Save creates the Geo in the database.
func (gc *GeoCreate) Save(ctx context.Context) (*Geo, error) {
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GeoCreate) SaveX(ctx context.Context) *Geo {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GeoCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GeoCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GeoCreate) check() error {
	if _, ok := gc.mutation.Point(); !ok {
		return &ValidationError{Name: "point", err: errors.New(`ent: missing required field "Geo.point"`)}
	}
	return nil
}

func (gc *GeoCreate) sqlSave(ctx context.Context) (*Geo, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GeoCreate) createSpec() (*Geo, *sqlgraph.CreateSpec) {
	var (
		_node = &Geo{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(entgeo.Table, sqlgraph.NewFieldSpec(entgeo.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.Point(); ok {
		_spec.SetField(entgeo.FieldPoint, field.TypeOther, value)
		_node.Point = value
	}
	return _node, _spec
}

// GeoCreateBulk is the builder for creating many Geo entities in bulk.
type GeoCreateBulk struct {
	config
	builders []*GeoCreate
}

// Save creates the Geo entities in the database.
func (gcb *GeoCreateBulk) Save(ctx context.Context) ([]*Geo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Geo, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GeoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GeoCreateBulk) SaveX(ctx context.Context) []*Geo {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GeoCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GeoCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
