// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tonimaru/try-ent/ent/fulltxt"
	entgeo "github.com/tonimaru/try-ent/ent/geo"
	"github.com/tonimaru/try-ent/ent/predicate"
	"github.com/tonimaru/try-ent/pkg/geo"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFulltxt = "Fulltxt"
	TypeGeo     = "Geo"
)

// FulltxtMutation represents an operation that mutates the Fulltxt nodes in the graph.
type FulltxtMutation struct {
	config
	op            Op
	typ           string
	id            *int
	txt           *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Fulltxt, error)
	predicates    []predicate.Fulltxt
}

var _ ent.Mutation = (*FulltxtMutation)(nil)

// fulltxtOption allows management of the mutation configuration using functional options.
type fulltxtOption func(*FulltxtMutation)

// newFulltxtMutation creates new mutation for the Fulltxt entity.
func newFulltxtMutation(c config, op Op, opts ...fulltxtOption) *FulltxtMutation {
	m := &FulltxtMutation{
		config:        c,
		op:            op,
		typ:           TypeFulltxt,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFulltxtID sets the ID field of the mutation.
func withFulltxtID(id int) fulltxtOption {
	return func(m *FulltxtMutation) {
		var (
			err   error
			once  sync.Once
			value *Fulltxt
		)
		m.oldValue = func(ctx context.Context) (*Fulltxt, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Fulltxt.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFulltxt sets the old Fulltxt of the mutation.
func withFulltxt(node *Fulltxt) fulltxtOption {
	return func(m *FulltxtMutation) {
		m.oldValue = func(context.Context) (*Fulltxt, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FulltxtMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FulltxtMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FulltxtMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FulltxtMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Fulltxt.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTxt sets the "txt" field.
func (m *FulltxtMutation) SetTxt(s string) {
	m.txt = &s
}

// Txt returns the value of the "txt" field in the mutation.
func (m *FulltxtMutation) Txt() (r string, exists bool) {
	v := m.txt
	if v == nil {
		return
	}
	return *v, true
}

// OldTxt returns the old "txt" field's value of the Fulltxt entity.
// If the Fulltxt object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FulltxtMutation) OldTxt(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTxt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTxt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTxt: %w", err)
	}
	return oldValue.Txt, nil
}

// ResetTxt resets all changes to the "txt" field.
func (m *FulltxtMutation) ResetTxt() {
	m.txt = nil
}

// Where appends a list predicates to the FulltxtMutation builder.
func (m *FulltxtMutation) Where(ps ...predicate.Fulltxt) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FulltxtMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FulltxtMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Fulltxt, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FulltxtMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FulltxtMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Fulltxt).
func (m *FulltxtMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FulltxtMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.txt != nil {
		fields = append(fields, fulltxt.FieldTxt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FulltxtMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case fulltxt.FieldTxt:
		return m.Txt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FulltxtMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case fulltxt.FieldTxt:
		return m.OldTxt(ctx)
	}
	return nil, fmt.Errorf("unknown Fulltxt field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FulltxtMutation) SetField(name string, value ent.Value) error {
	switch name {
	case fulltxt.FieldTxt:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTxt(v)
		return nil
	}
	return fmt.Errorf("unknown Fulltxt field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FulltxtMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FulltxtMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FulltxtMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Fulltxt numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FulltxtMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FulltxtMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FulltxtMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Fulltxt nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FulltxtMutation) ResetField(name string) error {
	switch name {
	case fulltxt.FieldTxt:
		m.ResetTxt()
		return nil
	}
	return fmt.Errorf("unknown Fulltxt field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FulltxtMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FulltxtMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FulltxtMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FulltxtMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FulltxtMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FulltxtMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FulltxtMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Fulltxt unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FulltxtMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Fulltxt edge %s", name)
}

// GeoMutation represents an operation that mutates the Geo nodes in the graph.
type GeoMutation struct {
	config
	op            Op
	typ           string
	id            *int
	point         **geo.Point
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Geo, error)
	predicates    []predicate.Geo
}

var _ ent.Mutation = (*GeoMutation)(nil)

// geoOption allows management of the mutation configuration using functional options.
type geoOption func(*GeoMutation)

// newGeoMutation creates new mutation for the Geo entity.
func newGeoMutation(c config, op Op, opts ...geoOption) *GeoMutation {
	m := &GeoMutation{
		config:        c,
		op:            op,
		typ:           TypeGeo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGeoID sets the ID field of the mutation.
func withGeoID(id int) geoOption {
	return func(m *GeoMutation) {
		var (
			err   error
			once  sync.Once
			value *Geo
		)
		m.oldValue = func(ctx context.Context) (*Geo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Geo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGeo sets the old Geo of the mutation.
func withGeo(node *Geo) geoOption {
	return func(m *GeoMutation) {
		m.oldValue = func(context.Context) (*Geo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GeoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GeoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GeoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GeoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Geo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPoint sets the "point" field.
func (m *GeoMutation) SetPoint(ge *geo.Point) {
	m.point = &ge
}

// Point returns the value of the "point" field in the mutation.
func (m *GeoMutation) Point() (r *geo.Point, exists bool) {
	v := m.point
	if v == nil {
		return
	}
	return *v, true
}

// OldPoint returns the old "point" field's value of the Geo entity.
// If the Geo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GeoMutation) OldPoint(ctx context.Context) (v *geo.Point, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPoint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPoint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPoint: %w", err)
	}
	return oldValue.Point, nil
}

// ResetPoint resets all changes to the "point" field.
func (m *GeoMutation) ResetPoint() {
	m.point = nil
}

// Where appends a list predicates to the GeoMutation builder.
func (m *GeoMutation) Where(ps ...predicate.Geo) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GeoMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GeoMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Geo, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GeoMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GeoMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Geo).
func (m *GeoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GeoMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.point != nil {
		fields = append(fields, entgeo.FieldPoint)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GeoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case entgeo.FieldPoint:
		return m.Point()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GeoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case entgeo.FieldPoint:
		return m.OldPoint(ctx)
	}
	return nil, fmt.Errorf("unknown Geo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GeoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case entgeo.FieldPoint:
		v, ok := value.(*geo.Point)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPoint(v)
		return nil
	}
	return fmt.Errorf("unknown Geo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GeoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GeoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GeoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Geo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GeoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GeoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GeoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Geo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GeoMutation) ResetField(name string) error {
	switch name {
	case entgeo.FieldPoint:
		m.ResetPoint()
		return nil
	}
	return fmt.Errorf("unknown Geo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GeoMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GeoMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GeoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GeoMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GeoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GeoMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GeoMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Geo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GeoMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Geo edge %s", name)
}
