// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Fulltxt is the predicate function for fulltxt builders.
type Fulltxt func(*sql.Selector)

// Geo is the predicate function for entgeo builders.
type Geo func(*sql.Selector)
